### PR TITLE
Added Georgia

### PR DESCRIPTION
**Pull request by RomaLetodiani**
I have added it in presets.go, if i have to do something else also please tell me in the comments.

### CODE REVIEW

**Review by ashkulz — APPROVED** [review]

**Comment by ashkulz** [comment]
Thanks for the contribution, @RomaLetodiani!

**Comment by ashkulz** [comment]
https://committers.top/georgia is now live :tada:

**Comment by RomaLetodiani** [comment]
Thank you for such a fast response!

**Comment by RomaLetodiani** [comment]
https://www.linkedin.com/posts/letodiani-roma_opensource-github-softwaredevelopment-activity-7216098603537211392-X_J7

**Pull request merged**
